name: darkbottomline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy=2.2.6
  - scipy=1.16.3
  - matplotlib=3.10.8
  - pandas=2.2.3
  - awkward=2.8.9
  - correctionlib=2.6.4
  - dask=2025.2.0
  - distributed=2025.2.0
  - scikit-learn=1.8.0
  - hist=2.9.0
  - plotly=5.16.1
  - pyarrow=20.0.0
  - pytest=8.4.2
  - jupyter=1.0.0
  - ipykernel=6.29.5
  - pyyaml=6.0.2
  - root=6.38.00
  - seaborn=0.13.2
  - tqdm=4.67.1
  - xrootd=5.9.1
  - pip
  - pip:
    - torch==2.10.0
    - coffea==2025.12.0
    - uproot==5.6.0
    - fsspec-xrootd==0.5.1
    - memory-profiler==0.61.0
