name: higgs-dna
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6,<3.12
  - pyaml
  - sphinx<7 # see https://github.com/readthedocs/readthedocs.org/issues/10279
  - breathe
  - sphinx_rtd_theme
  - sphinx-argparse
  - nbsphinx
  - ipywidgets
  - nbconvert>=5.5.0
  - jinja2>=3.0.3
  - pandoc
